53 исправить рендер страницы досок изменить дизайн страниц входа и регистрации
frontend-park-mail-ru/2023_2_yablonka pull request #13
Opened 2023-11-06 20:43 UTC by wolpy01

2023-11-07 09:37 UTC, johnSamilin requested changes

2023-11-07 09:37 UTC, johnSamilin commented on src/components/core/errorMessageAnimation.js
> +export default function errorMessageAnimation(errorClass, errorName, message) {
не уверен, что это core, это скорее utils, потому что core - это функционал, без которого ничего не заработает. Например, базовый класс Component

2023-11-07 09:37 UTC, johnSamilin commented on src/components/uploadAvatarModal/uploadAvatarModal.js
> +    constructor(parent, config) {
можно упростить все такие вот простые компоненты до вида:
`export default class UploadAvatarModal extends Component {
#name = 'uploadAvatarModal';
}`

2023-11-07 09:37 UTC, johnSamilin commented on static/css/style_card_modal.css
> +    font-family: 'Ubuntu';
а почему эти шрифты подключаются в стилях компонента? это же вроде общий стиль

2023-11-07 09:37 UTC, johnSamilin commented on static/css/style_card_modal.css
> +.page {
и вот эти стили тоже

2023-11-07 09:37 UTC, johnSamilin commented on static/css/style_card_modal.css
> +    color: #c0c9f4;
а вот эти цвета не конфигурируемы? они используются в нескольких местах, разве не надо их в переменные?

2023-11-07 09:37 UTC, johnSamilin commented on static/css/style_popover.css
> +    background-color: rgb(38, 44, 49);
а почему везде hex цвета, а тут rgb?

2023-11-07 09:37 UTC, johnSamilin commented on static/html/board.html
> +<!DOCTYPE html>
у вас же уже рабочее SPA, зачем тут эта страница?

2023-11-07 13:01 UTC, Glibusss commented on static/css/style_card_modal.css
> +    font-family: 'Ubuntu';
Это временно, далее будет SCSS отдельно с ними

2023-11-07 13:01 UTC, Glibusss commented on static/html/board.html
> +<!DOCTYPE html>
Забыли убрать

2023-11-07 16:20 UTC, johnSamilin commented on static/css/style_card_modal.css
> +    font-family: 'Ubuntu';
так он уже есть, чуть нижу

2023-11-07 17:29 UTC, johnSamilin approved these changes

2023-11-08 08:32 UTC, johnSamilin commented on router/router.js
>  router.use(express.static(path.resolve(__dirname, '../src')));
а зачем тут два обработчика для src?

2023-11-08 08:34 UTC, johnSamilin commented on src/modules/router.js
> +        console.log(redirectedPath, matchedView, this.signedInViews.get(matchedView));
лишние логи

2023-11-08 08:37 UTC, johnSamilin commented on src/view/board.js
> +        const [w, wsID, b, bID, c, cID] = window.location.pathname.shift().split('_');
вот тут бы по-хорошему передавать только boardId, чтобы по этому id из стора (или из бека) получать id всех связанных сущностей. что будет, если я напишу здесь в урле рандомные id-ники?

2023-11-08 08:37 UTC, johnSamilin commented on src/view/boards.js
> +            if(e.target.tagName==)
ой

2023-11-08 08:38 UTC, johnSamilin commented on src/view/profile.js
> +    async goProfileHandler(e) {
а где await?

2023-11-10 22:22 UTC, Glibusss commented
Вот тут надо ревью SW

2023-11-11 07:57 UTC, johnSamilin commented on src/components/Main/main.scss
> +@import './workspace/workspace.scss';
импорт стиля для компонента должен быть в самом компоненте

2023-11-11 08:14 UTC, johnSamilin requested changes

2023-11-11 08:14 UTC, johnSamilin commented on src/components/popups/changeAvatar/changeAvatar.js
> +    static addEventListeners() {
а почему static? вы же создаете экземпляр для того, чтобы отрендерить.
вот конкретно для него и надо включать обработчики, то есть` addEventListeners = () => { this.parent.querySelector(<уникальный класс компонента>).addEventListener`

2023-11-11 08:14 UTC, johnSamilin commented on src/components/popups/navigation/navigation.js
> +    #innerConfig = {
хорошая идея!

2023-11-11 08:14 UTC, johnSamilin commented on src/sw.js
> +const CacheKey = `cache-tabula-${new Date()}`;
с таким ключом нет смысла в кеше, он всегда уникальный, следовательно, кеш всегда протухший

2023-11-11 08:14 UTC, johnSamilin commented on src/sw.js
> +    const timeoutId = setTimeout(reject, timeout);
а зачем таймаут? у запроса в ветке .catch лучше проверить есть ли сеть через navigator.onLine или navigator.connection

2023-11-11 08:14 UTC, johnSamilin commented on static/scss/vars.scss
> +    --hover-navigation-paragraph: rgba(38, 44, 49, 1);
кайф

2023-11-12 19:57 UTC, Glibusss commented on src/sw.js
> +    const timeoutId = setTimeout(reject, timeout);
Вроде как поменял

2023-11-12 19:57 UTC, Glibusss commented on src/sw.js
> +const CacheKey = `cache-tabula-${new Date()}`;
Это исправил

2023-11-14 03:03 UTC, Glibusss commented
Что-то не так с получением воркспейсов при входе

2023-11-14 10:25 UTC, johnSamilin commented on src/components/Common/error/errorMessage.hbs
> +    style='color: #F46285;'
а почему это не в стилях?

2023-11-14 10:25 UTC, johnSamilin commented on src/components/Profile/userAvatar/userAvatar.js
> +        return template({
а в чем отличие? везде используется insertAdjacentHTML, а тут return

2023-11-14 10:25 UTC, johnSamilin commented on src/components/baseStyles.scss
> +@import './Profile/Profile.scss';
а зачем в базовые стили подмешивать профиль и главную?

2023-11-14 10:25 UTC, johnSamilin commented on src/components/core/popeventProcessing.js
> +    document.querySelector('.page').addEventListener('click', popeventProcess);
то есть клик по любому элементу на странице, даже если он внутри попапа, приведет к его закрытию?

2023-11-14 10:25 UTC, johnSamilin commented on src/components/popups/changeAvatar/changeAvatar.js
> +        document
лучше this.parent.querySelector

2023-11-14 10:25 UTC, johnSamilin commented on src/components/popups/uploadAvatar/uploadAvatar.js
> +    readFileAsByteArray(file) {
Этот метод может удолить, если он не нужен?

2023-11-14 10:25 UTC, johnSamilin commented on src/pages/Signup/signup.js
> +        if (!Validator.validateEmail(user.email)) {
а где реакции на неправильную валидацию?

2023-11-14 10:25 UTC, johnSamilin commented on src/sw.js
> +            return cache.addAll(['/index.html', '/img/', '/svg/']);
добавление целой папки не сработает, нужно по отдельности ресурсы добавлять

2023-11-16 00:21 UTC, Glibusss commented on src/components/Profile/userAvatar/userAvatar.js
> +        return template({
Тут возвращает HTML для более крупного компонента

2023-11-16 00:22 UTC, Glibusss commented on src/components/popups/uploadAvatar/uploadAvatar.js
> +    readFileAsByteArray(file) {
Пока нет, нужно решить вопрос с аватарками

2023-11-16 00:22 UTC, Glibusss commented on src/pages/Signup/signup.js
> +        if (!Validator.validateEmail(user.email)) {
Будут

2023-12-06 20:09 UTC, johnSamilin approved these changes

2023-12-06 20:10 UTC, merged