18 статическое окно регистрации
frontend-park-mail-ru/2023_2_yablonka pull request #2
Opened 2023-09-26 15:12 UTC by Glibusss

2023-09-26 15:48 UTC, johnSamilin requested changes

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +  height: 100%;
здесь лучше использовать min-height, потому что на главной контента может быть сильно больше высоты страницы

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +  height: 100%;
тут тоже

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +.container {
этот контейнер лучше обозвать понятней, например, login-page

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +.container__image-right {
модификаторы через _ же пишутся

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +  transform: scale(-1, 1);
а зачем такая трансформация? чтобы развернуть ее по горизонтали?

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +  width: fit-content;
если вы используете БЭМ, то `position`, `width` и `height` - это свойства класса `.container__image`, а у `.container__image_left` должны остаться `left` и `bottom`

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +.container__signup-location__header {
это не по БЭМу, опять же
`.container` тут лиший

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +  display: flex;
строки 83-86 как будто можно в отдельный класс выделить, типа `.centered-content` или типа того

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +.container__signup-location__header-registration {
почему повторяющиеся классы?

2023-09-26 15:48 UTC, johnSamilin commented on static/css/style.css
> +.container__signup-location__email {
это все можно назвать блоком `.input`

2023-09-26 15:48 UTC, johnSamilin commented on static/html/signup.html
> +<html lang="en">
точно язык страницы английский?

2023-09-26 15:48 UTC, johnSamilin commented on static/html/signup.html
> +    <title>Signup</title>
Лучше назвать страницы информативнее. К примеру, префикс `Tabula:` добавить

2023-09-26 15:48 UTC, johnSamilin commented on static/html/signup.html
> +          <span class="container__signup-location__logo"></span>Tabula
Тут текст куда-то убежал

2023-09-26 15:48 UTC, johnSamilin commented on static/html/signup.html
> +        <img src="../svg/undraw_team_collaboration.svg" />
Изображения можно не оборачивать в div, с тем же успехом можно повесить класс на img. А еще изображениям нужен alt

2023-09-26 15:48 UTC, johnSamilin commented on static/html/signup.html
> +          <a class="href-registration" href="#">Уже есть аккаунт?</a>
сюда уже можно поставить настоящую ссылку на вход

2023-09-26 15:49 UTC, johnSamilin commented
![image](https://github.com/frontend-park-mail-ru/2023_2_yablonka/assets/5821894/a3001bcf-442b-4ee4-8c6b-6aaaf5331cfe)
![image](https://github.com/frontend-park-mail-ru/2023_2_yablonka/assets/5821894/50f68bdb-2424-4a63-909a-9b90257c96d6)
Вы пока не делаете адаптивную верстку?

2023-09-26 19:15 UTC, johnSamilin commented on static/html/signup.html
> +        <form class="container__signup-location__form">
еще нужны параметры action и method

2023-09-26 19:15 UTC, johnSamilin commented on static/html/signup.html
> +          <button class="button-registration">Зарегистрироваться</button>
type="submit"

2023-09-26 22:05 UTC, Glibusss commented on static/css/style.css
> +  transform: scale(-1, 1);
https://htmlbook.ru/faq/kak-otrazit-izobrazhenie
Вот тут пишут, что ок

2023-09-29 10:06 UTC, johnSamilin approved these changes

2023-09-29 10:06 UTC, johnSamilin commented on static/css/style.css
> +.signup-form__container img {
`.signup-form__input img`, а то получается что вообще все изображения на этой форме будут такими

2023-09-30 16:16 UTC, merged