23 разбить на компоненты регистрацию
frontend-park-mail-ru/2023_2_yablonka pull request #7
Opened 2023-10-01 09:56 UTC by Glibusss

2023-10-01 12:56 UTC, johnSamilin requested changes

2023-10-01 12:56 UTC, johnSamilin commented on index.js
> +const express = require("express");
Снова какие-то лишние файлы

2023-10-01 12:56 UTC, johnSamilin commented on public/static/css/style_main.css
> +.icon {
абслютно все иконки будут такого размера?

2023-10-01 12:56 UTC, johnSamilin commented on public/static/js/components/background/Background.js
> +    console.log(Handlebars);
console.log надо убирать, это отладочный инструмент

2023-10-01 12:56 UTC, johnSamilin commented on public/static/js/components/background/Background.js
> +    const template = Handlebars.compile["Background.hbs"];
эту строчку лучше перенести в конструктор, чтобы не компилировать шаблон при каждой перерисовке, а сделать это 1 раз и использовать в методе render уже скомпилированный шаблон

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/backgroundImage/backgroundImage.js
> +        this.#parent.innerHTML += items.reduce((pictures, picture) => pictures + template(picture), "");
при каждой перерисовке этот компонент будет дублироваться

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/forgottenPassword/forgottenPassword.js
> +    constructor(parent, config) {
попробуйте выделить класс Component, где будет общий для всех компонентов код

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/formComponent/formComponent.js
> +        this.#parent.innerHTML += template();
здесь тоже будет дублироваться

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/formComponent/formComponent.js
> +        this.#parent.innerHTML += template();
если это намеренное поведение, добавьте комментарий о том, почему сделано именно так

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/forgottenPassword/forgottenPassword.js
> +        const template = Handlebars.templates["forgottenPassword.hbs"];
а почему где-то compile используется, а где-то templates?

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/formTitle/formTitle.js
> +    get items() {
это скорее data, потому что items - это массив данных для списка например

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/mainLogo/mainLogo.hbs
> +<span class="sign-location__name"></span>{{this.title}}
текст убежал за границы span

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/precompiler
> +if [ -f /JSscripts.txt ]; then
служебные скрипты принято убирать в отдельное место, например, в папку tools на корневом уровне

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/precompiler
> +    touch JSscripts.txt
кстати, на винде это не сработает. если вам это ок, то надо это в readme подсветить

2023-10-01 12:56 UTC, johnSamilin commented on static/js/components/precompiler
> +    echo "<script src="../js/components/$el/$el.precompile.js"></script>" >> ./JSscripts.txt
при каждой компиляции у меня не будет дублирования в этом файле?

2023-10-01 16:37 UTC, Glibusss commented on static/js/components/formTitle/formTitle.js
> +    get items() {
Сделано

2023-10-01 16:37 UTC, Glibusss commented on static/js/components/mainLogo/mainLogo.hbs
> +<span class="sign-location__name"></span>{{this.title}}
Сделано

2023-10-01 16:37 UTC, Glibusss commented on public/static/css/style_main.css
> +.icon {
Сделано

2023-10-01 16:37 UTC, Glibusss commented on public/static/js/components/background/Background.js
> +    console.log(Handlebars);
Это лишнее

2023-10-01 16:38 UTC, Glibusss commented on public/static/js/components/background/Background.js
> +    const template = Handlebars.compile["Background.hbs"];
Тоже лишний файл

2023-10-01 16:38 UTC, Glibusss commented on public/static/js/components/background/Background.js
> +    const template = Handlebars.compile["Background.hbs"];
Но идея классная

2023-10-01 16:38 UTC, Glibusss commented on static/js/components/backgroundImage/backgroundImage.js
> +        this.#parent.innerHTML += items.reduce((pictures, picture) => pictures + template(picture), "");
ТАк и задумано

2023-10-02 06:45 UTC, johnSamilin commented on static/js/components/signComponents/forgottenPassword/forgottenPassword.hbs
> +    {{this.text}}
кажется, тут в макросах не надо this использовать, достаточно просто text

2023-10-02 06:45 UTC, johnSamilin commented on static/js/components/signComponents/forgottenPassword/forgottenPassword.js
> +            (inputs, input) => inputs + this.template(input),
а почему в шаблоне речь про ссылку, а в компоненте - про input? и почему в методе render их якобы несколько?

2023-10-02 06:45 UTC, johnSamilin commented on static/js/components/signComponents/signHref/signHref.js
> +        this.parent.innerHTML += this.data.reduce(
правильней было бы `this.parent.innerHTML += this.template(this.data)`

2023-10-02 06:45 UTC, johnSamilin commented on static/js/pages/signInPage.js
> +        this.#root.style.backgroundColor = "#37426d";
а почему установка цвета здесь, а не в css?

2023-10-02 06:45 UTC, johnSamilin commented on static/js/pages/signInPage.js
> +        document.querySelector(".href-sign").addEventListener("click", (e) => {
во-первых, селектор неправильный, наверное должен быть `.href-signup`
во-вторых, добавление обработчиков должно быть в самом компоненте.
при этом, если вам нужно, чтобы обработчик вызывал какой-то код из другого компонента, как тут, то надо колбек в компонент прокинуть, как-то так:

```
class SingIn {
    onSignupLinkClicked() { ... }

    renderPage() {
        ...
        const signHref = new SignHref(formSelector, this.signinConfig.signHref);
        signHref.onClick = this.onSignupLinkClicked;
        ...
    }
}

class SignHref extends Component {
    addEventListeners() {
        <...>addEventListener('click', <вызов переданного onClick>)   
    }

    render() {
        ...
        this.addEventListeners()
    }
}
```

2023-10-02 06:45 UTC, johnSamilin commented on static/js/signIn.js
> +        history.pushState(null, null, "signup");
каеф

2023-10-02 06:45 UTC, johnSamilin commented on static/js/signIn.js
> +"use strict";
этот код дублируется в двух файлах, может стоит назвать один из них App.js и просто подключать на всех страницах?

2023-10-30 19:08 UTC, closed without merging