24 разбить на компоненты список досок
frontend-park-mail-ru/2023_2_yablonka pull request #9
Opened 2023-10-04 15:04 UTC by Glibusss

Тут деплой

2023-10-04 19:57 UTC, johnSamilin requested changes

2023-10-04 19:57 UTC, johnSamilin commented on README.md
> +Для установки express, handlebars - команда npm i(или install) express handlebars
эти пакеты уже есть в `package.json`, то есть достаточно выполнить `npm i`
кстати, чтобы добавить пакет в dev зависимости, можно его установить через `npm i --save-dev` и тогда `npm i` установит и его

2023-10-04 19:57 UTC, johnSamilin commented on static/js/components/core/ajax/ajax.js
> +        request = new Request(url, {
если разница между двумя объектами только в `body`, то лучше создавать запрос в одном месте
```
const params = { ... }
...
if (condition) {
    request.body = JSON.stringify
}

const request = new Request(url, params)
```

2023-10-04 19:57 UTC, johnSamilin commented on static/js/index.js
> +const logged = await AJAX("http://213.219.215.40:8080/api/v1/auth/verify/", "GET")
как вариант, можно этот запрос убрать в метод модуля AJAX и вызывать его просто типа `const logged = await AJAX.verify()`

2023-10-04 19:57 UTC, johnSamilin commented on static/js/index.js
> +    .then((res) => res.json())
и сюда еще добавить `.then(res => res.body)`, чтобы в logged сразу находилась нужная инфа

2023-10-05 23:47 UTC, Glibusss commented on static/js/components/core/ajax/ajax.js
> +        request = new Request(url, {
Мне почему-то пишет, что нельзя задать body

2023-10-05 23:47 UTC, Glibusss commented on static/js/index.js
> +const logged = await AJAX("http://213.219.215.40:8080/api/v1/auth/verify/", "GET")
Сделали

2023-10-05 23:49 UTC, Glibusss commented on README.md
> +Для установки express, handlebars - команда npm i(или install) express handlebars
Ок

2023-10-06 07:20 UTC, johnSamilin approved these changes

2023-10-06 09:36 UTC, merged